development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: francesmash_staging

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: francesmash_production
